config-version: 2

name: 'stripe'
version: '0.0.1'

require-dbt-version: ">=0.17.0"

models:
    stripe:
        materialized: table
        intermediate:
            materialized: table #ephemeral

profile: integration_test
